import Link from "next/link"
import { Container } from "./container"
import { siteConfig } from "@/config/site.config"

export const Footer = () => {
  return (
    <Container>
      <footer className="border-t border-border py-6 text-center text-sm text-muted-foreground">
        Generated by -{" "}
        <Link
          href={siteConfig.url}
          target="_blank"
          className="font-medium text-foreground underline-offset-4 hover:underline"
        >
          {siteConfig.name}.
        </Link>
      </footer>
    </Container>
  )
}
